export type Skills =
  | "JavaScript"
  | "TypeScript"
  | "React"
  | "NodeJS"
  | "HTML"
  | "CSS"
  | "Sass"
  | "Tailwind CSS"
  | "Python"
  | "MongoDB"
  | "PostgreSQL"
  | "MySQL"
  | "Selenium"
  | "Mocha"
  | "Linux"
  | "Docker"
  | "Git"
  | "Adobe XD"
  | "Adobe Photoshop"
  | "Adobe Illustrator"
  | "Figma"
  | "WordPress"
  | "Directus";