export type Skills =
  | "Adobe Illustrator"
  | "Adobe Photoshop"
  | "Adobe XD"
  | "Astro"
  | "AWS"
  | "CSS"
  | "Directus"
  | "Docker"
  | "Figma"
  | "Git"
  | "HTML"
  | "JavaScript"
  | "Linux"
  | "Mocha"
  | "MongoDB"
  | "MySQL"
  | "Next.js"
  | "Node.js"
  | "PHP"
  | "PostgreSQL"
  | "Python"
  | "React"
  | "Redis"
  | "SanityCMS"
  | "Sass"
  | "Selenium"
  | "Tailwind CSS"
  | "TypeScript"
  | "WordPress"