

export enum Skills {
  "AdobePhotoshop" = "Adobe Photoshop",
  "AdobeXD" = "Adobe XD",
  "Astro" = "Astro",
  "AWS" = "AWS",
  "CSS" = "CSS",
  "Directus" = "Directus",
  "Docker" = "Docker",
  "Figma" = "Figma",
  "Git" = "Git",
  "HTML" = "HTML",
  "JavaScript" = "JavaScript",
  "Linux" = "Linux",
  "Mocha" = "Mocha",
  "MongoDB" = "MongoDB",
  "MySQL" = "MySQL",
  "Nextjs" = "Next.js",
  "Nodejs" = "Node.js",
  "PHP" = "PHP",
  "PostgreSQL" = "PostgreSQL",
  "Python" = "Python",
  "React" = "React",
  "Redis" = "Redis",
  "SanityCMS" = "SanityCMS",
  "Sass" = "Sass",
  "Selenium" = "Selenium",
  "TailwindCSS" = "Tailwind CSS",
  "TypeScript" = "TypeScript",
  "WordPress" = "WordPress",
  "Redux" = "Redux",
  "GraphQL" = "GraphQL",
  "Jest" = "Jest",
  "Apollo" = "Apollo",
  "Zod" = "Zod",
  "Vite" = "Vite",
  "Vitest" = "Vitest",
  "ReactQuery" = "React Query",
  "TestingLibrary" = "Testing Library",
  "ReactRouter" = "React Router",
  "Webpack" = "Webpack",
  "Webstorm" = "Webstorm",
  "VSCode" = "VS Code",
  "Yarn" = "Yarn",
  "SonarQube" = "Sonar Qube"
}
